default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: rails101

test:
  <<: *default
  database: rails101

production:
  <<: *default
  database: rails101
